"""rename passwocrd to password

Revision ID: 1f7a532dab1a
Revises: 5eaafbbe7c1b
Create Date: 2026-04-24 11:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7a532dab1a'
down_revision = '5eaafbbe7c1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermsg', schema=None) as batch_op:
        batch_op.alter_column('passwocrd', new_column_name='password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermsg', schema=None) as batch_op:
        batch_op.alter_column('password', new_column_name='passwocrd')
    # ### end Alembic commands ###
