"""add email_verification_code table

Revision ID: 453ae5e5f3d1
Revises: 
Create Date: 2026-04-23 10:17:54.479448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453ae5e5f3d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_code',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('c_memo', sa.Text(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verification_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verification_code_email'), ['email'], unique=False)

    op.create_table('usermsg',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account', sa.String(length=150), nullable=False),
    sa.Column('user_name', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_stat', sa.SmallInteger(), nullable=True),
    sa.Column('c_memo', sa.Text(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('account')
    )
    op.create_table('daily_schedule',
    sa.Column('sche_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('v_date', sa.Date(), nullable=False),
    sa.Column('v_title', sa.String(length=255), nullable=False),
    sa.Column('v_content', sa.Text(), nullable=True),
    sa.Column('is_stat', sa.SmallInteger(), nullable=True),
    sa.Column('account', sa.String(length=150), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account'], ['usermsg.account'], ),
    sa.PrimaryKeyConstraint('sche_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_schedule')
    op.drop_table('usermsg')
    with op.batch_alter_table('email_verification_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verification_code_email'))

    op.drop_table('email_verification_code')
    # ### end Alembic commands ###
